"""
==========================================================
Request Logging Middleware
==========================================================

Logs every incoming HTTP request and outgoing response.

Responsibilities
----------------
- Generate or propagate request IDs
- Log incoming HTTP requests
- Log outgoing HTTP responses
- Measure request processing time
- Attach request metadata to responses
- Log unexpected exceptions

Compatible With
---------------
- FastAPI
- Starlette
- Uvicorn
- Docker
- Python 3.12+
==========================================================
"""

from __future__ import annotations

import time
from collections.abc import Callable
from uuid import uuid4

from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware

from app.core.logging import get_logger

logger = get_logger(__name__)


class LoggingMiddleware(BaseHTTPMiddleware):
    """
    Middleware responsible for logging the complete lifecycle
    of every HTTP request.

    Responsibilities
    ----------------
    - Generate or propagate request IDs
    - Measure request processing time
    - Log request start
    - Log request completion
    - Log unexpected exceptions
    - Add diagnostic response headers
    """

    async def dispatch(
        self,
        request: Request,
        call_next: Callable,
    ) -> Response:
        """
        Process an incoming HTTP request.

        Parameters
        ----------
        request:
            Incoming FastAPI request.

        call_next:
            Next middleware or route handler.

        Returns
        -------
        Response
            HTTP response generated by the application.
        """

        # --------------------------------------------------
        # Start request timer
        # --------------------------------------------------

        start_time = time.perf_counter()

        # --------------------------------------------------
        # Reuse the incoming request ID if provided.
        # Otherwise generate a new UUID.
        # --------------------------------------------------

        request_id = request.headers.get(
            "X-Request-ID",
            str(uuid4()),
        )

        # Store the request ID so it can be accessed
        # throughout the request lifecycle.
        request.state.request_id = request_id

        # --------------------------------------------------
        # Determine the client IP address.
        # --------------------------------------------------

        client_ip = (
            request.client.host
            if request.client
            else "unknown"
        )

        # --------------------------------------------------
        # Log the incoming request.
        # --------------------------------------------------

        logger.info(
            "Request Started | id=%s | %s %s | client=%s",
            request_id,
            request.method,
            request.url.path,
            client_ip,
        )

        try:

            # Process the request.
            response = await call_next(request)

        except Exception:

            # Calculate total processing time before logging.
            elapsed = (
                time.perf_counter() - start_time
            ) * 1000

            logger.exception(
                "Request Failed | id=%s | %s %s | %.2f ms",
                request_id,
                request.method,
                request.url.path,
                elapsed,
            )

            # Re-raise the exception so the global exception
            # handlers can generate the appropriate response.
            raise

        # --------------------------------------------------
        # Calculate request processing time.
        # --------------------------------------------------

        elapsed = (
            time.perf_counter() - start_time
        ) * 1000

        # --------------------------------------------------
        # Add diagnostic headers.
        # --------------------------------------------------

        response.headers["X-Request-ID"] = request_id
        response.headers["X-Process-Time"] = f"{elapsed:.2f}"

        # --------------------------------------------------
        # Log the completed request.
        # --------------------------------------------------

        logger.info(
            "Request Completed | id=%s | %s %s | Status=%s | %.2f ms",
            request_id,
            request.method,
            request.url.path,
            response.status_code,
            elapsed,
        )

        return response


__all__ = [
    "LoggingMiddleware",
]