"""
===============================================================================
User Model
===============================================================================

Database model representing an authenticated platform user.

Responsibilities
----------------
• Represent authenticated platform users.
• Store authentication credentials.
• Store authorization/RBAC information.
• Track account activation state.
• Track audit timestamps.
• Define ownership of user notes.
• Provide optimized database indexes.

Authentication
--------------
The User model stores the password hash only.

Plain-text passwords must never be persisted in this model or database.

Authorization
-------------
The ``role`` column stores the application's role value used by the
authentication and authorization layers.

JWT
---
FastAPI remains the JWT authority.

The JWT layer may expose claims such as:

• user_id
• email
• role

JWT creation and validation do NOT belong to this ORM model.

Database
--------
PostgreSQL

ORM
---
SQLAlchemy 2.x

Migrations
----------
Alembic

Python
------
3.12+
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    DateTime,
    Index,
    Integer,
    String,
    true,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.constants import PASSWORD_MAX_LENGTH, UserRole
from app.db.base import Base
from app.utils.datetime import utc_now

if TYPE_CHECKING:
    from app.models.note import Note


class User(Base):
    """
    Database model representing a platform user.

    A user participates in authentication and authorization and can own
    multiple notes.

    Attributes
    ----------
    id:
        Database-generated integer primary key.

    email:
        Unique user email address.

    hashed_password:
        Password hash generated by the application's security layer.

    role:
        Application authorization role.

    is_active:
        Indicates whether the account is currently active.

    created_at:
        UTC timestamp indicating when the account was created.

    updated_at:
        UTC timestamp indicating when the account was last updated.

    notes:
        Collection of notes owned by the user.
    """

    __tablename__ = "users"

    # =========================================================================
    # Database Indexes
    # =========================================================================
    #
    # These indexes support the application's common user-management
    # operations:
    #
    # • Authentication lookup by email.
    # • Administrative filtering by role.
    # • Filtering active/inactive accounts.
    #
    # The email column is also UNIQUE. The explicit index is retained because
    # it is part of the established database design and should not be removed
    # casually without reviewing the existing Alembic migration history.
    #
    __table_args__ = (
        Index("idx_users_email", "email"),
        Index("idx_users_role", "role"),
        Index("idx_users_is_active", "is_active"),
    )

    # =========================================================================
    # Primary Key
    # =========================================================================

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # =========================================================================
    # Authentication
    # =========================================================================

    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=False,
    )

    hashed_password: Mapped[str] = mapped_column(
        String(PASSWORD_MAX_LENGTH * 2),
        nullable=False,
    )

    # =========================================================================
    # Authorization / Account State
    # =========================================================================

    role: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default=UserRole.USER.value,
        server_default=UserRole.USER.value,
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default=true(),
    )

    # =========================================================================
    # Audit Timestamps
    # =========================================================================

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )

    # =========================================================================
    # Relationships
    # =========================================================================

    notes: Mapped[list[Note]] = relationship(
        "Note",
        back_populates="owner",
        cascade="all, delete-orphan",
        passive_deletes=True,
        lazy="select",
    )

    # =========================================================================
    # Representation
    # =========================================================================

    def __repr__(self) -> str:
        """
        Return a developer-friendly representation of the user.

        The password hash is intentionally excluded.

        The ``notes`` relationship is also excluded so representation of a
        User instance cannot deliberately traverse the relationship and
        trigger additional database loading.
        """

        return (
            "User("
            f"id={self.id}, "
            f"email={self.email!r}, "
            f"role={self.role!r}, "
            f"is_active={self.is_active}"
            ")"
        )


__all__ = [
    "User",
]